DierenasielBreda.EmployeeWebGUI/Controllers/AdministrationController.cs
using DierenasielBreda.EmployeeWebGUI.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DierenasielBreda.EmployeeWebGUI.Controllers
{
    [Authorize(Roles ="Admin, Medewerker")]
    public class AdministrationController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<IdentityUser> userManager;

        public AdministrationController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        [HttpGet]
        public IActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityRole identityRole = new IdentityRole
                {
                    Name = model.RoleName
                };
                IdentityResult result = await roleManager.CreateAsync(identityRole);

                if (result.Succeeded)
                {
                    return RedirectToAction("List", "Dier");
                }

                foreach(IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }   
            return View(model);
        }

        [HttpGet]
        public IActionResult ListRoles()
        {
            var roles = roleManager.Roles;
            return View(roles);
        }

        // Role ID is passed from the URL to the action
        [HttpGet]
        public async Task<IActionResult> EditRole(string id)
        {
            // Find the role by Role ID
            var role = await roleManager.FindByIdAsync(id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {id} cannot be found";
                return View("NotFound");
            }

            var model = new EditRoleViewModel
            {
                Id = role.Id,
                RoleName = role.Name
            };

            // Krijg alle users
            foreach (var user in userManager.Users)
            {
                // If the user is in this role, add the username to
                // Users property of EditRoleViewModel. This model
                // object is then passed to the view for display
                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    model.Users.Add(user.UserName);
                }
            }
            return View(model);
        }

        // This action responds to HttpPost and receives EditRoleViewModel
        [HttpPost]
        public async Task<IActionResult> EditRole(EditRoleViewModel model)
        {
            var role = await roleManager.FindByIdAsync(model.Id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {model.Id} cannot be found";
                return View("NotFound");
            }
            else
            {
                role.Name = model.RoleName;

                // Update the Role using UpdateAsync
                var result = await roleManager.UpdateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListRoles");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View(model);
            }
        }

        [HttpGet]
        public async Task<IActionResult> EditUsersInRole(string roleId)
        {
            ViewBag.roleId = roleId;

            var role = await roleManager.FindByIdAsync(roleId);

            if(role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {roleId} cannot be found";
                return View("NotFound");
            }

            var model = new List<UserRoleViewModel>();

            foreach(var user in userManager.Users)
            {
                var userRoleViewModel = new UserRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName
                };

                if(await userManager.IsInRoleAsync(user, role.Name))
                {
                    userRoleViewModel.IsSelected = true;
                }
                else
                {
                    userRoleViewModel.IsSelected = false;
                }

                model.Add(userRoleViewModel);
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditUsersInRole(List<UserRoleViewModel> model, string roleId)
        {
            var role = await roleManager.FindByIdAsync(roleId);

            if(role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {roleId} cannot be found";
                return View("NotFound");
            }

            for(int i = 0; i < model.Count; i++)
            {
                var user = await userManager.FindByIdAsync(model[i].UserId);

                IdentityResult result = null;

                if(model[i].IsSelected && !(await userManager.IsInRoleAsync(user, role.Name)))
                {
                    result = await userManager.AddToRoleAsync(user, role.Name);
                }
                else if(!model[i].IsSelected && await userManager.IsInRoleAsync(user, role.Name))
                {
                    result = await userManager.RemoveFromRoleAsync(user, role.Name);
                }
                else
                {
                    continue;
                }

                if (result.Succeeded)
                {
                    if (i < (model.Count - 1))
                        continue;
                    else
                        return RedirectToAction("EditRole", new {  Id = roleId});
                }
            }
            return RedirectToAction("EditRole", new { Id = roleId });
        }
    }
}

DierenasielBreda.EmployeeWebGUI/Controllers/DierController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DierenasielBreda.Core.DomainModel;
using DierenasielBreda.Core.DomainServices;
using DierenasielBreda.EmployeeWebGUI.Models.ViewModels;
using System.Threading;
using Microsoft.AspNetCore.Authorization;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DierenasielBreda.EmployeeWebGUI.Controllers
{
    [Authorize(Roles = "Vrijwilliger, Medewerker, Admin")]
    public class DierController : Controller
    {
        private IDierRepository repository;
        private IVacatureDierRepository vRepository;
        private IVerblijfRepository verblijfRepository;
        public int PageSize = 25;

        

        public DierController(IDierRepository repo,IVacatureDierRepository vRepo, IVerblijfRepository verblijfRepo)
        {
            repository = repo;
            vRepository = vRepo;
            verblijfRepository = verblijfRepo;
        }

        [AllowAnonymous]
        public async Task<ViewResult> List(string category, int Page = 1) => View(new DierListViewModel
        {
            Dieren = await repository.GetDierenAsync(),

            PagingInfo = new PagingInfo
            {
                CurrentPage = Page,
                ItemsPerPage = PageSize,
                TotalItems = category == null ?
                    repository.GetDieren().Count() :
                repository.GetDieren().Where(e => e.Ras == category).Count()
            },
            CurrentCategory = category
        });

        [HttpGet]
        public ViewResult Add()
        {
            return View();
        }
        [HttpGet]
        public ViewResult AddWithId(int Id)
        {
            var vDier = vRepository.GetVacatureDier(Id);

            var dier = new AddDierViewModel
            {
                Naam = vDier.Naam,
                Geboortedatum = default,
                GeschatteLeeftijd = default,
                Omschrijving = null,
                Diersoort = vDier.Diersoort,
                Ras = null,
                Geslacht = vDier.Geslacht,
                Foto = null,
                DatumBinnenkomst = default,
                Gecastreerd = vDier.Gecastreerd,
                KanMetKinderen = null,
                RedenAfstand = vDier.RedenAfstand,
                Adopteerbaar = default
            };
            return View("Add", dier);
        }
        
        [HttpPost]
        public async Task<ViewResult> Add(AddDierViewModel model)
        {
            if (ModelState.IsValid)
            {

                var dier = new Dier
                {
                    Naam = model.Naam,
                    Geboortedatum = model.Geboortedatum,
                    Leeftijd = calculateAge(model.Geboortedatum),
                    GeschatteLeeftijd = model.GeschatteLeeftijd,
                    Omschrijving = model.Omschrijving,
                    Diersoort = model.Diersoort,
                    Ras = model.Ras,
                    Geslacht = model.Geslacht,
                    Foto = model.Foto,
                    DatumBinnenkomst = model.DatumBinnenkomst,
                    DatumAdoptie = null,
                    DatumOverlijden = null,
                    Gecastreerd = model.Gecastreerd,
                    KanMetKinderen = model.KanMetKinderen,
                    Opmerking = null,
                    RedenAfstand = model.RedenAfstand,
                    Adopteerbaar = model.Adopteerbaar,
                    VerblijfId = getVerblijf(model)
                   
                };

                
                if(dier.VerblijfId == 0)
                {
                    return View("Confirmation", dier);
                }

                await repository.AddDierAsync(dier);
                
                return View("Confirmation", dier);
            }
            else
            {
                return View("Add");
            }
            
        }
        [HttpGet]
        public IActionResult Detail(int Id)
        {
            Dier dier = repository.GetDier(Id);
            return View(dier);
        }
        public ViewResult Confirmation()
        {
            return View();
        }

        private int calculateAge(DateTime start)
        {
            /*
            int age = 0;
            age = DateTime.Now.Year - start.Year;
            if (DateTime.Now.DayOfYear < start.DayOfYear)
                age = age - 1;

            return age;*/

            DateTime end = DateTime.Now;
            return (end.Year - start.Year - 1) +
                (((end.Month > start.Month) ||
                ((end.Month == start.Month) && (end.Day >= start.Day))) ? 1 : 0);
        }

        private int getVerblijf(AddDierViewModel model)
        {
            var verblijven = verblijfRepository.GetVerblijven();
            if (model.Individueel == true)
            {
                foreach (Verblijf verblijf in verblijven)
                {
                    if (verblijf.Capaciteit == 1 && verblijf.Dieren == null && verblijf.Diersoort == model.Diersoort)
                    {
                        return verblijf.Id;
                    }
                }
            }
            else
            {
                foreach (Verblijf verblijf in verblijven)
                {
                    if (verblijf.Dieren == null || verblijf.Dieren.Count() < verblijf.Capaciteit)
                    {
                        if(model.Gecastreerd == true)
                        {
                            if (verblijf.Castratie == true && verblijf.Capaciteit > 1 && verblijf.Diersoort == model.Diersoort)
                            {
                                return verblijf.Id;
                            }
                        }
                        else
                        {
                            if (verblijf.Castratie == false && verblijf.Geslacht == model.Geslacht && verblijf.Capaciteit > 1 && verblijf.Diersoort == model.Diersoort)
                            {
                                return verblijf.Id;
                            }
                        }   
                    }
                }
            }
            
            return 0;
        }
    }
}

DierenasielBreda.EmployeeWebGUI/Controllers/VacatureDierController.cs
using DierenasielBreda.Core.DomainModel;
using DierenasielBreda.Core.DomainServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DierenasielBreda.EmployeeWebGUI.Controllers
{
    //[Authorize(Roles ="Klant")]
    public class VacatureDierController : Controller
    {
        private IVacatureDierRepository repository;
        private IVerblijfRepository verblijfRepository;
        public VacatureDierController(IVacatureDierRepository repo, IVerblijfRepository verblijfRepo)
        {
            repository = repo;
            verblijfRepository = verblijfRepo;
        }
        [Authorize(Roles = "Klant")]
        [HttpGet]
        public ViewResult Create()
        {
            ViewBag.plaatsenTotaalKat = getTotalPlaatsenKat();
            ViewBag.plaatsenTotaalHond = getTotalPlaatsenHond();
            return View();
        }
        [Authorize(Roles = "Klant")]
        [HttpPost]
        public async Task<ViewResult> Create(VacatureDier model)
        {


            if (ModelState.IsValid)
            {
                var vDier = new VacatureDier
                {
                    Naam = model.Naam,
                    Diersoort = model.Diersoort,
                    Geslacht = model.Geslacht,
                    Gecastreerd = model.Gecastreerd,
                    RedenAfstand = model.RedenAfstand,
                };

                await repository.AddVacatureDierAsync(vDier);

                return View("Confirmation", vDier);
            }
            else
            {
                return View("Add");
            }
        }
        [Authorize(Roles = "Vrijwilliger, Medewerker, Admin")]
        [HttpGet]
        public async Task<ViewResult> List()
        {
            var vDier = await repository.GetVacatureDierenAsync();
            return View(vDier);
        }

        [Authorize(Roles = "Vrijwilliger, Medewerker, Admin")]
        [HttpGet]
        public IActionResult Delete(int Id)
        {
            //ViewBag.roleId = Id;
            VacatureDier vDier = repository.GetVacatureDier(Id);
            return View(vDier);
        }
        [Authorize(Roles = "Vrijwilliger, Medewerker, Admin")]
        [HttpPost]
        public IActionResult Delete(VacatureDier vDier)
        {

            repository.DeleteVacatureDier(vDier.Id);

            return RedirectToAction("List");
        }

        private int getTotalPlaatsenHond()
        {
            int honden = 0;
            int capaciteit = 0;
            foreach(Verblijf verblijf in verblijfRepository.GetVerblijven())
            {
                if(verblijf.Diersoort == "Hond")
                {
                    capaciteit += verblijf.Capaciteit;
                    if (verblijf.Dieren != null)
                    {
                        int x = verblijf.Dieren.Count();
                        honden += x;
                    }
                }     
            }
            int result = (capaciteit - honden);
            return result;
        }
        private int getTotalPlaatsenKat()
        {
            int katten = 0;
            int capaciteit = 0;
            foreach (Verblijf verblijf in verblijfRepository.GetVerblijven())
            {
                if(verblijf.Diersoort == "Kat")
                {
                    capaciteit += verblijf.Capaciteit;
                    if (verblijf.Dieren != null)
                    {
                        katten += verblijf.Dieren.Count();
                    }
                }            
            }
            int result = (capaciteit - katten);
            return result;
        }
    }
}

DierenasielBreda.EmployeeWebGUI/Views/Shared/DierSummary.cshtml
@model Dier
@inject SignInManager<IdentityUser> signInManager;



<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            <img src="@Model.Foto" class="rounded float-left" width="100" , height="100">
            @Model.Naam
            <span class="badge badge-pill badge-primary" style="float:right">
                <small>@Model.Ras</small>
                <small>@Model.Geboortedatum</small>
            </span>
        </h4>
    </div>
    <span class="card-text p-1">
        @Model.Omschrijving
        @if (User.IsInRole("Admin") || User.IsInRole("Medewerker"))
        {     
            <div class="pull-right">
                <a style="text-emphasis-position:right" asp-controller="Dier" asp-action="Detail" asp-route-id="@Model.Id" class="btn btn-success btn-sm pull-right">Detail</a>
            </div>
            /*<button type="submit" asp-controller="Dier" asp-action="Detail" asp-route-id="@Model.Id" class="btn btn-success btn-sm pull-right" style="float:right">
                Details
            </button>*/
        }
    </span>
</div>

DierenasielBreda.EmployeeWebGUI/Views/Shared/_Layout.cshtml
@inject SignInManager<IdentityUser> signInManager;


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DierenasielBreda.EmployeeWebGUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>



        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Dier" asp-action="List">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    @if (User.IsInRole("Klant"))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VacatureDier" asp-action="Create">Dier ter adoptie stellen</a>
                        </li>
                    }
                    @if (User.IsInRole("Admin") || User.IsInRole("Medewerker") || User.IsInRole("Vrijwilliger"))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VacatureDier" asp-action="List">Vacature Dieren</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dier" asp-action="Add">Dier toevoegen</a>
                        </li>
                    }
                    @if (User.IsInRole("Admin") || User.IsInRole("Medewerker"))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Administration" asp-action="ListRoles">Roles</a>
                        </li>
                    }
                </ul>
            </div>
            <div class="mx-auto order-0">
                <!--<a class="navbar-brand mx-auto" href="#">Navbar 2</a>-->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                <ul class="navbar-nav ml-auto">
                    @if (signInManager.IsSignedIn(User))
                    {
                        <li class="nav-item">
                            <form method="post" asp-area="" asp-controller="Account" asp-action="Logout">
                                <button type="submit" class="nav-link btn btn-link py-0" style="width:auto">
                                    Logout @User.Identity.Name
                                </button>
                            </form>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                    }
                </ul>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - DierenasielBreda.EmployeeWebGUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>