DierenasielBreda.EmployeeWebGUI/Controllers/DierController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DierenasielBreda.Core.DomainModel;
using DierenasielBreda.Core.DomainServices;
using DierenasielBreda.EmployeeWebGUI.Models.ViewModels;
using System.Threading;
using Microsoft.AspNetCore.Authorization;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DierenasielBreda.EmployeeWebGUI.Controllers
{
    [Authorize(Roles = "Vrijwilliger, Medewerker, Admin")]
    public class DierController : Controller
    {
        private IDierRepository repository;
        private IVacatureDierRepository vRepository;
        private IVerblijfRepository verblijfRepository;
        public int PageSize = 25;

        

        public DierController(IDierRepository repo,IVacatureDierRepository vRepo, IVerblijfRepository verblijfRepo)
        {
            repository = repo;
            vRepository = vRepo;
            verblijfRepository = verblijfRepo;
        }

        [AllowAnonymous]
        public async Task<ViewResult> List(string category, int Page = 1) => View(new DierListViewModel
        {
            Dieren = await repository.GetDierenAsync(),

            PagingInfo = new PagingInfo
            {
                CurrentPage = Page,
                ItemsPerPage = PageSize,
                TotalItems = category == null ?
                    repository.GetDieren().Count() :
                repository.GetDieren().Where(e => e.Ras == category).Count()
            },
            CurrentCategory = category
        });

        [HttpGet]
        public ViewResult Add()
        {
            return View();
        }
        [HttpGet]
        public ViewResult AddWithId(int Id)
        {
            var vDier = vRepository.GetVacatureDier(Id);

            var dier = new AddDierViewModel
            {
                Naam = vDier.Naam,
                Geboortedatum = default,
                GeschatteLeeftijd = default,
                Omschrijving = null,
                Diersoort = vDier.Diersoort,
                Ras = null,
                Geslacht = vDier.Geslacht,
                Foto = null,
                DatumBinnenkomst = default,
                Gecastreerd = vDier.Gecastreerd,
                KanMetKinderen = null,
                RedenAfstand = vDier.RedenAfstand,
                Adopteerbaar = default
            };
            return View("Add", dier);
        }
        
        [HttpPost]
        public async Task<ViewResult> Add(AddDierViewModel model)
        {
            if (ModelState.IsValid)
            {

                var dier = new Dier
                {
                    Naam = model.Naam,
                    Geboortedatum = model.Geboortedatum,
                    Leeftijd = calculateAge(model.Geboortedatum),
                    GeschatteLeeftijd = model.GeschatteLeeftijd,
                    Omschrijving = model.Omschrijving,
                    Diersoort = model.Diersoort,
                    Ras = model.Ras,
                    Geslacht = model.Geslacht,
                    Foto = model.Foto,
                    DatumBinnenkomst = model.DatumBinnenkomst,
                    DatumAdoptie = null,
                    DatumOverlijden = null,
                    Gecastreerd = model.Gecastreerd,
                    KanMetKinderen = model.KanMetKinderen,
                    Opmerking = null,
                    RedenAfstand = model.RedenAfstand,
                    Adopteerbaar = model.Adopteerbaar,
                    VerblijfId = getVerblijf(model)
                   
                };

                
                if(dier.VerblijfId == 0)
                {
                    return View("Confirmation", dier);
                }

                await repository.AddDierAsync(dier);
                
                return View("Confirmation", dier);
            }
            else
            {
                return View("Add");
            }
            
        }
        [HttpGet]
        public IActionResult Detail(int Id)
        {
            Dier dier = repository.GetDier(Id);
            return View(dier);
        }
        public ViewResult Confirmation()
        {
            return View();
        }

        private int calculateAge(DateTime start)
        {
            /*
            int age = 0;
            age = DateTime.Now.Year - start.Year;
            if (DateTime.Now.DayOfYear < start.DayOfYear)
                age = age - 1;

            return age;*/

            DateTime end = DateTime.Now;
            return (end.Year - start.Year - 1) +
                (((end.Month > start.Month) ||
                ((end.Month == start.Month) && (end.Day >= start.Day))) ? 1 : 0);
        }

        private int getVerblijf(AddDierViewModel model)
        {
            var verblijven = verblijfRepository.GetVerblijven();
            if (model.Individueel == true)
            {
                foreach (Verblijf verblijf in verblijven)
                {
                    if (verblijf.Capaciteit == 1 && verblijf.Dieren == null && verblijf.Diersoort == model.Diersoort)
                    {
                        return verblijf.Id;
                    }
                }
            }
            else
            {
                foreach (Verblijf verblijf in verblijven)
                {
                    if (verblijf.Dieren == null || verblijf.Dieren.Count() < verblijf.Capaciteit)
                    {
                        if(model.Gecastreerd == true)
                        {
                            if (verblijf.Castratie == true && verblijf.Capaciteit > 1 && verblijf.Diersoort == model.Diersoort)
                            {
                                return verblijf.Id;
                            }
                        }
                        else
                        {
                            if (verblijf.Castratie == false && verblijf.Geslacht == model.Geslacht && verblijf.Capaciteit > 1 && verblijf.Diersoort == model.Diersoort)
                            {
                                return verblijf.Id;
                            }
                        }   
                    }
                }
            }
            
            return 0;
        }
    }
}

DierenasielBreda.EmployeeWebGUI/Controllers/VacatureDierController.cs
using DierenasielBreda.Core.DomainModel;
using DierenasielBreda.Core.DomainServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DierenasielBreda.EmployeeWebGUI.Controllers
{
    //[Authorize(Roles ="Klant")]
    public class VacatureDierController : Controller
    {
        private IVacatureDierRepository repository;
        private IVerblijfRepository verblijfRepository;
        public VacatureDierController(IVacatureDierRepository repo, IVerblijfRepository verblijfRepo)
        {
            repository = repo;
            verblijfRepository = verblijfRepo;
        }
        [Authorize(Roles = "Klant")]
        [HttpGet]
        public ViewResult Create()
        {
            ViewBag.plaatsenTotaalKat = getTotalPlaatsenKat();
            ViewBag.plaatsenTotaalHond = getTotalPlaatsenHond();
            return View();
        }
        [Authorize(Roles = "Klant")]
        [HttpPost]
        public async Task<ViewResult> Create(VacatureDier model)
        {


            if (ModelState.IsValid)
            {
                var vDier = new VacatureDier
                {
                    Naam = model.Naam,
                    Diersoort = model.Diersoort,
                    Geslacht = model.Geslacht,
                    Gecastreerd = model.Gecastreerd,
                    RedenAfstand = model.RedenAfstand,
                };

                await repository.AddVacatureDierAsync(vDier);

                return View("Confirmation", vDier);
            }
            else
            {
                return View("Add");
            }
        }
        [Authorize(Roles = "Vrijwilliger, Medewerker, Admin")]
        [HttpGet]
        public async Task<ViewResult> List()
        {
            var vDier = await repository.GetVacatureDierenAsync();
            return View(vDier);
        }

        [Authorize(Roles = "Vrijwilliger, Medewerker, Admin")]
        [HttpGet]
        public IActionResult Delete(int Id)
        {
            //ViewBag.roleId = Id;
            VacatureDier vDier = repository.GetVacatureDier(Id);
            return View(vDier);
        }
        [Authorize(Roles = "Vrijwilliger, Medewerker, Admin")]
        [HttpPost]
        public IActionResult Delete(VacatureDier vDier)
        {

            repository.DeleteVacatureDier(vDier.Id);

            return RedirectToAction("List");
        }

        private int getTotalPlaatsenHond()
        {
            int honden = 0;
            int capaciteit = 0;
            foreach(Verblijf verblijf in verblijfRepository.GetVerblijven())
            {
                if(verblijf.Diersoort == "Hond")
                {
                    capaciteit += verblijf.Capaciteit;
                    if (verblijf.Dieren != null)
                    {
                        int x = verblijf.Dieren.Count();
                        honden += x;
                    }
                }     
            }
            int result = (capaciteit - honden);
            return result;
        }
        private int getTotalPlaatsenKat()
        {
            int katten = 0;
            int capaciteit = 0;
            foreach (Verblijf verblijf in verblijfRepository.GetVerblijven())
            {
                if(verblijf.Diersoort == "Kat")
                {
                    capaciteit += verblijf.Capaciteit;
                    if (verblijf.Dieren != null)
                    {
                        katten += verblijf.Dieren.Count();
                    }
                }            
            }
            int result = (capaciteit - katten);
            return result;
        }
    }
}

DierenasielBreda.EmployeeWebGUI/Views/VacatureDier/Confirmation.cshtml
@model VacatureDier;

@if (Model != null)
{
    <h1>@Model.Naam is ter adoptie gesteld!</h1>
    <div>
        <a asp-controller="Dier" asp-action="List">Back to List</a>
    </div>
}
else
{
    <h1>Oh nee er ging wat fout!</h1>
}

DierenasielBreda.EmployeeWebGUI/Views/VacatureDier/Create.cshtml
@model DierenasielBreda.Core.DomainModel.VacatureDier

@{
    ViewData["Title"] = "View";
}
<h1>VacatureDier</h1>
<!--<h2>Plaatsen over katten: ViewBag.plaatsenTotaalKat</h2>
<h2>Plaatsen over honden: ViewBag.plaatsenTotaalHond</h2>
    -->
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="View">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Naam" class="control-label"></label>
                <input asp-for="Naam" class="form-control" />
                <span asp-validation-for="Naam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Diersoort" class="control-label"></label>
                <input asp-for="Diersoort" class="form-control" />
                <span asp-validation-for="Diersoort" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    @Html.RadioButtonFor(m => m.Geslacht, "true")Male
                </label>
                <label class="form-check-label">
                    @Html.RadioButtonFor(m => m.Geslacht, "false")Female
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Gecastreerd" /> @Html.DisplayNameFor(model => model.Gecastreerd)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="RedenAfstand" class="control-label"></label>
                <input asp-for="RedenAfstand" class="form-control" />
                <span asp-validation-for="RedenAfstand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DierenasielBreda.EmployeeWebGUI/Views/VacatureDier/Delete.cshtml
@model DierenasielBreda.Core.DomainModel.VacatureDier

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>VacatureDier</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Naam)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Naam)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Diersoort)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Diersoort)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Geslacht)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Geslacht)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gecastreerd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gecastreerd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RedenAfstand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RedenAfstand)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DierenasielBreda.EmployeeWebGUI/Views/VacatureDier/List.cshtml
@model IEnumerable<DierenasielBreda.Core.DomainModel.VacatureDier>

@{
    ViewData["Title"] = "List";
}

<h1>List</h1>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Naam)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Diersoort)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Geslacht)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gecastreerd)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RedenAfstand)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Naam)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Diersoort)
            </td>
            <td>
                @if (item.Geslacht == true)
                {
                    <p>Male</p>
                }
                else
                {
                    <p>Female</p>
                }
            </td>
            <td>
                @if (item.Gecastreerd == true)
                {
                    <p>Ja</p>
                }
                else
                {
                    <p>Nee</p>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RedenAfstand)
            </td>
            <td>
                <a asp-controller="Dier" asp-action="AddWithId" asp-route-id="@item.Id">Verwerken</a>
                <a asp-controller="VacatureDier" asp-action="Delete" asp-route-id="@item.Id">Delete</a>

 
            </td>
        </tr>
}
    </tbody>
</table>